server:
  port: 8080

spring:
  datasource:
    #主数据源
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      jdbc-url: jdbc:mysql://localhost:3306/vhr?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
      username: root
      password: 123
    #从数据源
    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      jdbc-url: jdbc:mysql://localhost:3306/ry?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
      username: root
      password: 123
  #双redis配置
  redis:
    host-name: localhost
    database: 0
    port: 6379
    password: 123
    timeout: 0
    lettuce:
      pool:
        max-active: -1 #连接池最大连接数（使用负值表示没有限制）
        max-wait: -1 # 连接池中的最大空闲连接
        max-idle: 8  # 当连接池耗尽时， 抛出异常之前，连接分配被阻塞的时间，也就是连接池满后最长等待时间，负值表示无限期等待
        min-idle: 0 #连接池中的最小空闲连接
  #用户缓存token的redis配置
  redis-token:
    host-name: localhost
    database: 1
    port: 6379
    password: 123


mybatis-plus:
  ##mapper.xml文件存放的路径
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
